name: GCP Deploy

on:
  workflow_dispatch:
    inputs:
      Version:
        description: '[debug|production]'     
        required: true
        default: 'production'

env:
  FRONTEND_DIR: ./frontend/client
  BACKEND_DIR: ./backend

jobs:

    deploy:

        name: deploy
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME_FRONTEND: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}-frontend
          IMAGE_NAME_BACKEND: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}-backend

        - name: Checkout repository
          uses: actions/checkout@v2
          with: 
            submodules: recursive

        - name: Push Docker image
          run: |
            docker push $IMAGE_NAME_FRONTEND
            docker push $IMAGE_NAME_BACKEND

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Build Docker image
          run: |
            docker build -f ./devops/debug/frontend/Dockerfile . -t $IMAGE_NAME_FRONTEND --build-arg FRONTEND_DIR=$FRONTEND_DIR --build-arg VER=$Version
            docker build -f ./devops/debug/backend/Dockerfile . -t $IMAGE_NAME_BACKEND --build-arg BACKEND_DIR=$BACKEND_DIR --build-arg VER=$Version

        # - name: Test Docker image
        #   run: docker run $IMAGE_NAME sh -c "go test -v"

        - name: Deploy Docker image
          run: |
            gcloud run deploy ${{ secrets.GCP_PROJECT_ID }}-frontend --image $IMAGE_NAME_FRONTEND --region northamerica-northeast2 --platform managed --port 3000
            gcloud run deploy ${{ secrets.GCP_PROJECT_ID }}-backend --image $IMAGE_NAME_BACKEND --region northamerica-northeast2 --platform managed --port 5000