name: main workflow

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        npm install --prefix ./client
        pip install -r ./backend/requirements.txt

    - name: Test Frontend
      continue-on-error: true
      run: |
        cd client && npm run test 

    - name: Test Backend
      continue-on-error: true
      run: |
        cd backend/anonymizer 
        pylint .
        pytest

    # - name: Build Docker Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: false
    #     tags: my-docker-registry/my-app:${{ github.sha }}
