name: main workflow

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        npm install --prefix ./client
        pip install -r ./backend/requirements.txt

    - name: Test Frontend
      continue-on-error: true
      run: |
        cd client && npm run test 

    - name: Test Backend
      continue-on-error: true
      run: |
        cd backend/anonymizer 
        pylint .
        pytest

    - name: Test Integration
      run: |
        echo "place holder";

    # call-workflow-gcp-deploy:
    #   use: ./.github/workflows/GCP-deploy-yml

