name: main workflow

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        npm install --prefix ./client
        pip install -r ./backend/requirements.txt

    - name: Test Frontend
      continue-on-error: true
      run: |
        cd client && npm run test 

    - name: Test Backend
      continue-on-error: true
      run: |
        cd backend/anonymizer 
        pylint .
        pytest

    - name: Test Integration
      run: |
        echo "place holder";

    

    # - name: Build Docker Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: false
    #     tags: my-docker-registry/my-app:${{ github.sha }}
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: |
    #       This is a release for version ${{ github.ref }} of the app.
    #     draft: false
    #     prerelease: false
    # - name: Upload Docker Image to Release
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: my-docker-registry/my-app:${{ github.sha }}
    #     asset_name: my-app-${{ github.sha }}.tar.gz
    #     asset_content_type: application/gzip